### ISSUE TITLE
Auto detect "rotateBvecsWithCanXform", "rotateBvecsWithRx" parameters

### ISSUE THREAD

**Issue by soichih** [brain-life/app-dtiinit#1]
Currently, users have to select correct options for following paramters

```
"rotateBvecsWithCanXform": false,
"rotateBvecsWithRx": false,
"eddyCorrect": "-1"
```

I believe most users are not familiar with the first 2 parameters and we should explore ways to auto-detect these parameters if possible. @bcmcpher Do you know if there is a way to do that?

**Comment by bcmcpher** [comment]
I don't think there will be. This is a preprocessing decision people have
to make. rotateBvecsWithCanXform() adjusts the bvecs with alignment to the
T1 and rotateBvecsWithRx adjusts the bvecs during motion / eddy correction.

If we really don't want people manipulating them, they should just be
locked on, honestly.

Brent

**Comment by soichih** [comment]
dtiInit's internal default for those parameters are both false, but @kitchell says that they almost always needs to be set to true - except for HCP project. So the defaults on this app are both set to true. To properly process HCP, user needs to flip it back to dtiInit's default (false).

If we can't automate this, we should do one or more of following.

1) Explain these parameters to death.. so that user can figure out what to do. Where to look, who to ask, etc..
2) For projects that default option won't work (user needs to manually switch it back to false), then provide preprocessed dtiInit output so that user can just use the output.
3) Implement capability on Brain-Life to override the application defaults at project level. For example, iIf user tries to run app-dtiinit on HCP data, it will automatically set those options to false - by default.

I think we should do 1) first,  then do either 2) or 3).

**Comment by soichih** [comment]
We now know that both of those bvecs flags should be set to true for HCP - without modifying the input bvecs like we used to. We've added a bit more description for those options as well. Closing.
